services:
  - type: web
    name: registration-form
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000"
    autoDeploy: true
    envVars:
      - key: PHP_VERSION
        value: 8.2
